"""link stock and user tables

Revision ID: 314b7d0b7502
Revises: 838ec018c247
Create Date: 2025-03-03 16:23:09.533409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314b7d0b7502'
down_revision = '838ec018c247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_stocks_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stocks_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
